#此工作流将使用 Maven 构建一个 Java 项目，并缓存/还原任何依赖项，以缩短工作流执行时间
#有关更多信息，请参阅： https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

名称： 爪哇 CI 与马文

在：
  workflow_dispatch:
  时间表：
    - 克朗：“8 0 * * *”

招聘职位：
  构建：

    run-on： ubuntu-latest

    步骤：
    - 用途：动作/checkout@v3
    - 名称：设置 JDK 11
      用途：操作/设置java@v3
      与：
        java 版本： '11'
        分布：“特穆林”
        缓存： maven
    - 名称： 与梅文一起建造
      运行： mvn -B 包 --文件 pom.xml
    - 名称： 运行爪哇
      run： java -jar ./target/VxMessageActions-1.0-SNAPSHOT.jar
      
    
